# Generated by Django 5.2.5 on 2025-11-04 23:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='field',
            new_name='major',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AddField(
            model_name='course',
            name='coursenumber',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(499)]),
        ),
    ]
